title: 李玫郁
description: Personal details
sitename: Mei-Yu Lee
baseurl: '/one-page-wonder-jekyll'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME